using System.Text.Json.Serialization;
using Tavstal.YggdrasilSharp.Models;
using Tavstal.YggdrasilSharp.Models.Attributes;
using Tavstal.YggdrasilSharp.Models.Bodies.Auth;
using Tavstal.YggdrasilSharp.Models.Bodies.Launcher;
using Tavstal.YggdrasilSharp.Models.Bodies.News;
using Tavstal.YggdrasilSharp.Models.Bodies.Yggdrasil;
using Tavstal.YggdrasilSharp.Models.Common;
using Tavstal.YggdrasilSharp.Models.Config;
using Tavstal.YggdrasilSharp.Models.Database;
using Tavstal.YggdrasilSharp.Models.Database.Launcher;
using Tavstal.YggdrasilSharp.Models.Database.Server;
using Tavstal.YggdrasilSharp.Models.Database.User;
using Tavstal.YggdrasilSharp.Models.Database.User.Claims;
using Tavstal.YggdrasilSharp.Models.RateLimiting;
using Tavstal.YggdrasilSharp.Models.RateLimiting.Rules;
using Tavstal.YggdrasilSharp.Models.Responses;
using Tavstal.YggdrasilSharp.Models.Responses.Auth;
using Tavstal.YggdrasilSharp.Models.Responses.News;
using Tavstal.YggdrasilSharp.Models.Responses.User;
using Tavstal.YggdrasilSharp.Models.Responses.Yggdrasil;

namespace Tavstal.YggdrasilSharp.Serialization;

/// <inheritdoc />
[JsonSerializable(typeof(AppConfiguration))]
[JsonSerializable(typeof(List<AppConfiguration>))]
[JsonSerializable(typeof(FileSaveResult))]
[JsonSerializable(typeof(List<FileSaveResult>))]
[JsonSerializable(typeof(Cape))]
[JsonSerializable(typeof(List<Cape>))]
[JsonSerializable(typeof(LauncherSignInResult))]
[JsonSerializable(typeof(List<LauncherSignInResult>))]
[JsonSerializable(typeof(SignInResult))]
[JsonSerializable(typeof(List<SignInResult>))]
[JsonSerializable(typeof(FileData))]
[JsonSerializable(typeof(List<FileData>))]
[JsonSerializable(typeof(News))]
[JsonSerializable(typeof(List<News>))]
[JsonSerializable(typeof(JsonResponseAttribute))]
[JsonSerializable(typeof(List<JsonResponseAttribute>))]
[JsonSerializable(typeof(FormFileAttribute))]
[JsonSerializable(typeof(List<FormFileAttribute>))]
[JsonSerializable(typeof(TextResponseAttribute))]
[JsonSerializable(typeof(List<TextResponseAttribute>))]
[JsonSerializable(typeof(EFileDataType))]
[JsonSerializable(typeof(List<EFileDataType>))]
[JsonSerializable(typeof(EFileSizeUnit))]
[JsonSerializable(typeof(List<EFileSizeUnit>))]
[JsonSerializable(typeof(ESkinType))]
[JsonSerializable(typeof(List<ESkinType>))]
[JsonSerializable(typeof(IpInfo))]
[JsonSerializable(typeof(List<IpInfo>))]
[JsonSerializable(typeof(JwtConfig))]
[JsonSerializable(typeof(List<JwtConfig>))]
[JsonSerializable(typeof(MiscConfig))]
[JsonSerializable(typeof(List<MiscConfig>))]
[JsonSerializable(typeof(SwaggerConfig))]
[JsonSerializable(typeof(List<SwaggerConfig>))]
[JsonSerializable(typeof(DatabaseConfig))]
[JsonSerializable(typeof(List<DatabaseConfig>))]
[JsonSerializable(typeof(YggdrasilConfig))]
[JsonSerializable(typeof(List<YggdrasilConfig>))]
[JsonSerializable(typeof(ProxyConfig))]
[JsonSerializable(typeof(List<ProxyConfig>))]
[JsonSerializable(typeof(EmailConfig))]
[JsonSerializable(typeof(List<EmailConfig>))]
[JsonSerializable(typeof(AgentConfig))]
[JsonSerializable(typeof(List<AgentConfig>))]
[JsonSerializable(typeof(RateLimiterData))]
[JsonSerializable(typeof(List<RateLimiterData>))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(List<ErrorResponse>))]
[JsonSerializable(typeof(ResponseBase))]
[JsonSerializable(typeof(List<ResponseBase>))]
[JsonSerializable(typeof(CustomRole))]
[JsonSerializable(typeof(List<CustomRole>))]
[JsonSerializable(typeof(CustomUser))]
[JsonSerializable(typeof(List<CustomUser>))]
[JsonSerializable(typeof(CustomUserClaim))]
[JsonSerializable(typeof(List<CustomUserClaim>))]
[JsonSerializable(typeof(CustomUserLogin))]
[JsonSerializable(typeof(List<CustomUserLogin>))]
[JsonSerializable(typeof(CustomUserRole))]
[JsonSerializable(typeof(List<CustomUserRole>))]
[JsonSerializable(typeof(CustomUserToken))]
[JsonSerializable(typeof(List<CustomUserToken>))]
[JsonSerializable(typeof(UserBackupCode))]
[JsonSerializable(typeof(List<UserBackupCode>))]
[JsonSerializable(typeof(UserBillingInformation))]
[JsonSerializable(typeof(List<UserBillingInformation>))]
[JsonSerializable(typeof(UserCape))]
[JsonSerializable(typeof(List<UserCape>))]
[JsonSerializable(typeof(UserPlaySession))]
[JsonSerializable(typeof(List<UserPlaySession>))]
[JsonSerializable(typeof(ServerJoin))]
[JsonSerializable(typeof(List<ServerJoin>))]
[JsonSerializable(typeof(ELauncherOs))]
[JsonSerializable(typeof(List<ELauncherOs>))]
[JsonSerializable(typeof(EVersionType))]
[JsonSerializable(typeof(List<EVersionType>))]
[JsonSerializable(typeof(LauncherVersionData))]
[JsonSerializable(typeof(List<LauncherVersionData>))]
[JsonSerializable(typeof(LauncherVersion))]
[JsonSerializable(typeof(List<LauncherVersion>))]
[JsonSerializable(typeof(ConfirmRegisterRequestBody))]
[JsonSerializable(typeof(List<ConfirmRegisterRequestBody>))]
[JsonSerializable(typeof(LauncherLoginRequestBody))]
[JsonSerializable(typeof(List<LauncherLoginRequestBody>))]
[JsonSerializable(typeof(LauncherLoginTFASessionRequestBody))]
[JsonSerializable(typeof(List<LauncherLoginTFASessionRequestBody>))]
[JsonSerializable(typeof(LoginRequestBody))]
[JsonSerializable(typeof(List<LoginRequestBody>))]
[JsonSerializable(typeof(LoginTFASessionRequestBody))]
[JsonSerializable(typeof(List<LoginTFASessionRequestBody>))]
[JsonSerializable(typeof(RecoverPasswordRequestBody))]
[JsonSerializable(typeof(List<RecoverPasswordRequestBody>))]
[JsonSerializable(typeof(RecoverTwoFactorRequestBody))]
[JsonSerializable(typeof(List<RecoverTwoFactorRequestBody>))]
[JsonSerializable(typeof(RegisterRequestBody))]
[JsonSerializable(typeof(List<RegisterRequestBody>))]
[JsonSerializable(typeof(YigProfileBody))]
[JsonSerializable(typeof(List<YigProfileBody>))]
[JsonSerializable(typeof(YigSignoutRequest))]
[JsonSerializable(typeof(List<YigSignoutRequest>))]
[JsonSerializable(typeof(YigJoinServerRequest))]
[JsonSerializable(typeof(List<YigJoinServerRequest>))]
[JsonSerializable(typeof(YigRefreshRequest))]
[JsonSerializable(typeof(List<YigRefreshRequest>))]
[JsonSerializable(typeof(YigValidateRequest))]
[JsonSerializable(typeof(List<YigValidateRequest>))]
[JsonSerializable(typeof(YigAgent))]
[JsonSerializable(typeof(List<YigAgent>))]
[JsonSerializable(typeof(YigInvalidateRequest))]
[JsonSerializable(typeof(List<YigInvalidateRequest>))]
[JsonSerializable(typeof(YigLoginRequest))]
[JsonSerializable(typeof(List<YigLoginRequest>))]
[JsonSerializable(typeof(YigUser))]
[JsonSerializable(typeof(List<YigUser>))]
[JsonSerializable(typeof(YigUserProperty))]
[JsonSerializable(typeof(List<YigUserProperty>))]
[JsonSerializable(typeof(UpdateLauncherVersionRequest))]
[JsonSerializable(typeof(List<UpdateLauncherVersionRequest>))]
[JsonSerializable(typeof(CreateLauncherVersionRequest))]
[JsonSerializable(typeof(List<CreateLauncherVersionRequest>))]
[JsonSerializable(typeof(CreateLauncherVersionDataRequest))]
[JsonSerializable(typeof(List<CreateLauncherVersionDataRequest>))]
[JsonSerializable(typeof(NewsCreateRequestBody))]
[JsonSerializable(typeof(List<NewsCreateRequestBody>))]
[JsonSerializable(typeof(NewsUpdateRequestBody))]
[JsonSerializable(typeof(List<NewsUpdateRequestBody>))]
[JsonSerializable(typeof(FixedWindowRule))]
[JsonSerializable(typeof(List<FixedWindowRule>))]
[JsonSerializable(typeof(SlidingWindowRule))]
[JsonSerializable(typeof(List<SlidingWindowRule>))]
[JsonSerializable(typeof(ConcurrentRule))]
[JsonSerializable(typeof(List<ConcurrentRule>))]
[JsonSerializable(typeof(TokenBucketRule))]
[JsonSerializable(typeof(List<TokenBucketRule>))]
[JsonSerializable(typeof(LoggedInResponse))]
[JsonSerializable(typeof(List<LoggedInResponse>))]
[JsonSerializable(typeof(LoginRedirectResponse))]
[JsonSerializable(typeof(List<LoginRedirectResponse>))]
[JsonSerializable(typeof(LoginResponse))]
[JsonSerializable(typeof(List<LoginResponse>))]
[JsonSerializable(typeof(LoginLauncherRedirectResponse))]
[JsonSerializable(typeof(List<LoginLauncherRedirectResponse>))]
[JsonSerializable(typeof(TwoFactorCodeResponse))]
[JsonSerializable(typeof(List<TwoFactorCodeResponse>))]
[JsonSerializable(typeof(TwoFactorSecretResponse))]
[JsonSerializable(typeof(List<TwoFactorSecretResponse>))]
[JsonSerializable(typeof(NewsResponseBody))]
[JsonSerializable(typeof(List<NewsResponseBody>))]
[JsonSerializable(typeof(YigErrorResponse))]
[JsonSerializable(typeof(List<YigErrorResponse>))]
[JsonSerializable(typeof(YigLoginResponse))]
[JsonSerializable(typeof(List<YigLoginResponse>))]
[JsonSerializable(typeof(YigRefreshResponse))]
[JsonSerializable(typeof(List<YigRefreshResponse>))]
[JsonSerializable(typeof(UserInfoResponse))]
[JsonSerializable(typeof(List<UserInfoResponse>))]
[JsonSerializable(typeof(CustomClaim))]
[JsonSerializable(typeof(List<CustomClaim>))]
[JsonSerializable(typeof(RoleClaim))]
[JsonSerializable(typeof(List<RoleClaim>))]
[JsonSerializable(typeof(UserClaim))]
[JsonSerializable(typeof(List<UserClaim>))]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(YigBlockedServersResponse))]
[JsonSerializable(typeof(YigStatusResponse))]
[JsonSerializable(typeof(YigProfileKeysResponse))]
[JsonSerializable(typeof(YigProfileResponse))]
[JsonSerializable(typeof(List<YigProfileResponse>))]
[JsonSourceGenerationOptions(DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull, UseStringEnumConverter = true)]
public partial class CustomJsonContext : JsonSerializerContext;
