using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.

namespace Tavstal.YggdrasilSharp.Models.Database.User;

/// <summary>
/// Represents a single backup code entry for a user.
/// 
/// Backup codes are typically one-time use codes provided as a fallback for
/// multifactor authentication (MFA) or account recovery. This entity stores
/// a hashed representation of the code along with timestamps indicating when
/// it was created and (optionally) when it was used.
/// </summary>
public class UserBackupCode
{
    /// <summary>
    /// Primary key for the UserBackupCode record.
    /// This value is generated by the database (identity/auto-increment).
    /// </summary>
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public ulong Id { get; set; }
    
    /// <summary>
    /// The identifier (UUID string) of the user this backup code belongs to.
    /// This is a foreign key that references the user table.
    /// </summary>
    [StringLength(36)]
    public string UserId { get; set; }
    
    /// <summary>
    /// The hashed representation of the backup code.
    /// </summary>
    [StringLength(256)]
    public string HashedCode { get; set; }
    
    /// <summary>
    /// The timestamp when this backup code was created.
    /// Stored as a <see cref="DateTimeOffset"/> to preserve timezone/offset information.
    /// </summary>
    public DateTimeOffset CreateAt { get; set; }
    
    /// <summary>
    /// The timestamp when this backup code was used. Null if the code has not been used yet.
    /// </summary>
    public DateTimeOffset? UsedAt { get; set; }
    
    /* ######################################################################
     *                         NAVIGATION PROPERTIES
     * ###################################################################### */
    
    /// <summary>
    /// Gets or sets the user associated with this UserCape record.
    /// This property is ignored during JSON serialization.
    /// </summary>
    [ForeignKey("UserId")] 
    [JsonIgnore]
    public CustomUser? User { get; set; } 
}